workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'  # Only run if manually triggered via UI
stages:
  - docker_build_and_push
  # - terraform_plan
  # - terraform_apply

variables:
  IMAGE_TAG: $CI_PIPELINE_ID
  DOCKER_IMAGE: "akshayreddy1155/simple-time-service"
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

docker_build_and_push_job:
  stage: docker_build_and_push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo "Building image $DOCKER_IMAGE:$IMAGE_TAG from ./app"
    - docker build -t $DOCKER_IMAGE:$IMAGE_TAG ./app
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push $DOCKER_IMAGE:$IMAGE_TAG
    - docker tag $DOCKER_IMAGE:$IMAGE_TAG $DOCKER_IMAGE:latest
    - docker push $DOCKER_IMAGE:latest
  only:
    - main
